# buy_binds/generator.py
from pathlib import Path


def generate_cfg(binds: list[dict], output_path: Path):
    """
    binds: [{"key": "f1", "commands": ["buy ak47", "buy flashbang"]}]
    Schreibt eine CS2-kompatible .cfg Datei.
    """
    lines = ["// Auto-generated by CS2 CFG Configurator", ""]
    for bind in binds:
        key = bind["key"]
        cmds = ";".join(bind["commands"])
        lines.append(f'bind "{key}" "{cmds}"')
    lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")
