# buy_binds/generator.py
from pathlib import Path


def generate_cfg(binds: list[dict], output_path: Path):
    """
    binds: [{"key": "k", "commands": ["buy ak47", "buy flashbang"]}]
    Erzeugt eine .cfg Datei mit den entsprechenden bind-Befehlen.
    """
    lines = ["// Auto-generated by CS2 CFG Configurator\n"]
    for bind in binds:
        key = bind["key"]
        cmds = ";".join(bind["commands"])
        lines.append(f'bind "{key}" "{cmds}"')
    lines.append("")  # Newline am Ende
    output_path.write_text("\n".join(lines), encoding="utf-8")
