# cfg_editor/generator.py
from pathlib import Path


def generate_cfg(entries: list[dict], output_path: Path):
    """
    entries: [{"command": "cl_crosshairsize", "value": "4"}]
    Schreibt eine CS2-kompatible .cfg Datei.
    """
    lines = [
        "// Auto-generated by vsvito's CounterStrike2 CFG Configurator – CFG Editor",
        f"// Category config – {output_path.stem}",
        "",
    ]
    for entry in entries:
        cmd = entry["command"]
        val = entry.get("value", "")
        if val == "":  # pure command like r_cleardecals
            lines.append(cmd)
        else:
            lines.append(f"{cmd} {val}")
    lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")
